# Generated by Django 2.2.5 on 2020-02-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='bookType',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='donate',
            name='desc',
            field=models.TextField(),
        ),
    ]
