# Generated by Django 2.2.5 on 2020-02-23 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basicApp', '0002_auto_20200221_0949'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donate',
            old_name='Author',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='donate',
            name='img',
        ),
        migrations.AddField(
            model_name='donate',
            name='image',
            field=models.ImageField(default='10', upload_to='pics/'),
        ),
        migrations.AddField(
            model_name='donate',
            name='owner',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
    ]
