# Generated by Django 2.2.5 on 2020-02-24 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicApp', '0003_auto_20200223_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donate',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='books', to=settings.AUTH_USER_MODEL),
        ),
    ]
